package com.pk.core.repay.port;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public interface LoanLenderBillRepository {
    void upsert(LoanLenderBillData data);

    List<LoanLenderBillData> findByUserIdAndBillStatuses(long userId, List<String> billStatuses);

    record LoanLenderBillData(
            String loanApplyId,
            long userId,
            String externalLoanApplyNo,
            String lenderUserId,
            String billNo,
            String contrNo,
            Integer terms,
            BigDecimal applyAmt,
            String currency,
            String userName,
            Long statusDate,
            String billStatus,
            BigDecimal feePrepayAmt,
            BigDecimal lendAmt,
            Long lendTime,
            String paySerialNo,
            Long dueDate,
            BigDecimal stampDuty,
            BigDecimal principal,
            BigDecimal interest,
            BigDecimal fee1,
            BigDecimal fee2,
            BigDecimal fee3,
            BigDecimal fee1Tax,
            BigDecimal fee2Tax,
            BigDecimal fee3Tax,
            BigDecimal prePenInterest,
            BigDecimal penInterest,
            BigDecimal initLateFee,
            Integer termNo,
            Long termDueDate,
            BigDecimal shouldStampDuty,
            BigDecimal shouldPrincipal,
            BigDecimal shouldInterest,
            BigDecimal shouldFee1,
            BigDecimal shouldFee2,
            BigDecimal shouldFee3,
            BigDecimal shouldFee1Tax,
            BigDecimal shouldFee2Tax,
            BigDecimal shouldFee3Tax,
            BigDecimal shouldPenInterest,
            BigDecimal shouldInitLateFee,
            BigDecimal paidStampDuty,
            BigDecimal paidPrincipal,
            BigDecimal paidInterest,
            BigDecimal paidFee1,
            BigDecimal paidFee2,
            BigDecimal paidFee3,
            BigDecimal paidFee1Tax,
            BigDecimal paidFee2Tax,
            BigDecimal paidFee3Tax,
            BigDecimal paidPenInterest,
            BigDecimal paidInitLateFee,
            BigDecimal paidAdvSettleFee,
            BigDecimal reductionStampDuty,
            BigDecimal reductionPrincipal,
            BigDecimal reductionInterest,
            BigDecimal reductionFee1,
            BigDecimal reductionFee2,
            BigDecimal reductionFee3,
            BigDecimal reductionFee1Tax,
            BigDecimal reductionFee2Tax,
            BigDecimal reductionFee3Tax,
            BigDecimal reductionPenInterest,
            BigDecimal reductionInitLateFee,
            BigDecimal reductionAdvSettleFee,
            Integer overdueDays,
            Long firstOverdueDay,
            Long lastRepayTime,
            Integer maxOverdueDays,
            Long paidOutDate,
            String advSetteFlag,
            Long externalInteractionId,
            Instant queriedAt
    ) {
    }
}
