package com.pk.infra.profile.repository;

/** Mutable row for MyBatis insert (generated id) and select. */
public class ProfileAfRow {
    public Long id;
    public Long profileId;
    public String mobileNo;
    public String appsflyerId;
    public String advertisingId;
    public String androidId;
    public String attributedTouchTime;
    public String gpClickTime;
    public String installTime;
    public String mediaSource;
    public String afPrt;
    public String afAdsetId;
    public String afAdset;
    public String afSiteid;
    public String afCId;
    public String campaign;
    public String appVersion;
    public String appId;
    public String deviceType;
    public String osVersion;
    public String countryCode;
    public String city;
    public String postalCode;
    public String ip;
    public String operator;
    public String deviceCategory;
    public String platform;
    public String deviceModel;
    public String idfv;
    public String idfa;
    public String afAd;
    public String afChannel;
    public String attributedTouchType;
    public String afAdId;
    public String afAdType;
    public String contributor1TouchType;
    public String contributor1TouchTime;
    public String contributor1AfPrt;
    public String contributor1MatchType;
    public String contributor1EngagementType;
    public String bundleId;
    public String matchType;
    public String gpInstallBegin;
    public String moduleStatus;
    public String requestId;
    public String lastLenderRequestJson;
    public String lastLenderResponseJson;
}
