spring:
  datasource:
    url: ${PK_DB_URL}
    username: ${PK_DB_USERNAME}
    password: ${PK_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

logging:
  level:
    root: WARN
    com.pk: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

pk:
  logging:
    sls:
      enabled: ${PK_SLS_ENABLED:true}
      endpoint: ${PK_SLS_ENDPOINT:ap-southeast-5.log.aliyuncs.com}
      project: ${PK_SLS_PROJECT:pk-backend-prod}
  lender:
    config:
      source: db
      provider-code: pendanaan
  worker:
    reference:
      enabled: true
