package com.pk.app.loan.dto.response;

import com.pk.infra.loan.LoanTrialFacade;
import java.math.BigDecimal;
import java.util.List;

public record LoanTrialResponse(
        String quoteNo,
        long expiresAt,
        String applyId,
        String creditApplyNo,
        String lenderUserId,
        BigDecimal applyAmt,
        String productCode,
        String repayMethod,
        Integer loanTerm,
        BigDecimal loanPrincipal,
        BigDecimal showLoanPrincipal,
        BigDecimal payAmount,
        BigDecimal handFee,
        BigDecimal schdAmount,
        BigDecimal shouldAmount,
        BigDecimal interest,
        BigDecimal dayRate,
        BigDecimal showDayRate,
        Long totalDays,
        String fee1Name,
        BigDecimal fee1,
        String fee2Name,
        BigDecimal fee2,
        String fee3Name,
        BigDecimal fee3,
        BigDecimal tax,
        String taxRatePercent,
        BigDecimal ppnAmount,
        BigDecimal shouldStampDuty,
        BigDecimal shouldPrincipal,
        BigDecimal shouldInterest,
        BigDecimal shouldFee1,
        BigDecimal shouldFee2,
        BigDecimal shouldFee3,
        BigDecimal shouldFee1Tax,
        BigDecimal shouldFee2Tax,
        BigDecimal shouldFee3Tax,
        BigDecimal reductionAmount,
        BigDecimal adReductionAmt,
        BigDecimal adReductionRatio,
        Long adReductionEndDate,
        BigDecimal reductionStampDuty,
        BigDecimal reductionPrincipal,
        BigDecimal reductionInterest,
        BigDecimal reductionFee1,
        BigDecimal reductionFee2,
        BigDecimal reductionFee3,
        BigDecimal reductionFee1Tax,
        BigDecimal reductionFee2Tax,
        BigDecimal reductionFee3Tax,
        String afterServiceFeeStatus,
        Integer feePrepayType,
        Long lendingDate,
        Long firstRepayDate,
        Long lastRepayDate,
        Boolean unevenBillsFlag,
        List<LoanTrialTermResponse> termInfo
) {
    public static LoanTrialResponse from(LoanTrialFacade.TrialResult result) {
        var quote = result.quote();
        return new LoanTrialResponse(
                result.quoteNo(),
                result.expiresAt(),
                quote.applyId(),
                quote.creditApplyNo(),
                quote.lenderUserId(),
                quote.applyAmt(),
                quote.productCode(),
                quote.repayMethod(),
                quote.loanTerm(),
                quote.loanPrincipal(),
                quote.showLoanPrincipal(),
                quote.payAmount(),
                quote.handFee(),
                quote.schdAmount(),
                quote.shouldAmount(),
                quote.interest(),
                quote.dayRate(),
                quote.showDayRate(),
                quote.totalDays(),
                quote.fee1Name(),
                quote.fee1(),
                quote.fee2Name(),
                quote.fee2(),
                quote.fee3Name(),
                quote.fee3(),
                quote.tax(),
                quote.taxRatePercent(),
                quote.ppnAmount(),
                quote.shouldStampDuty(),
                quote.shouldPrincipal(),
                quote.shouldInterest(),
                quote.shouldFee1(),
                quote.shouldFee2(),
                quote.shouldFee3(),
                quote.shouldFee1Tax(),
                quote.shouldFee2Tax(),
                quote.shouldFee3Tax(),
                quote.reductionAmount(),
                quote.adReductionAmt(),
                quote.adReductionRatio(),
                quote.adReductionEndDate(),
                quote.reductionStampDuty(),
                quote.reductionPrincipal(),
                quote.reductionInterest(),
                quote.reductionFee1(),
                quote.reductionFee2(),
                quote.reductionFee3(),
                quote.reductionFee1Tax(),
                quote.reductionFee2Tax(),
                quote.reductionFee3Tax(),
                quote.afterServiceFeeStatus(),
                quote.feePrepayType(),
                quote.lendingDate(),
                quote.firstRepayDate(),
                quote.lastRepayDate(),
                quote.unevenBillsFlag(),
                result.termInfo().stream().map(LoanTrialTermResponse::from).toList()
        );
    }
}
