package com.pk.app.loan.dto.response;

import com.pk.infra.loan.LoanTrialFacade;
import java.math.BigDecimal;

public record LoanTrialTermResponse(
        int termNo,
        String termNoDisplay,
        Long valueDate,
        String valueDateDisplay,
        Long dueDate,
        String dueDateDisplay,
        Long graceDate,
        String graceDateDisplay,
        BigDecimal schdAmount,
        String schdAmountDisplay,
        BigDecimal schdPrincipal,
        String schdPrincipalDisplay,
        BigDecimal showLoanPrincipal,
        String showLoanPrincipalDisplay,
        BigDecimal schdInterest,
        String schdInterestDisplay,
        BigDecimal showInterest,
        String showInterestDisplay,
        BigDecimal shouldAmount,
        String shouldAmountDisplay,
        BigDecimal shouldPrincipal,
        String shouldPrincipalDisplay,
        BigDecimal shouldInterest,
        String shouldInterestDisplay,
        BigDecimal fee1,
        String fee1Display,
        BigDecimal fee2,
        String fee2Display,
        BigDecimal fee3,
        String fee3Display,
        BigDecimal fee1Tax,
        String fee1TaxDisplay,
        BigDecimal fee2Tax,
        String fee2TaxDisplay,
        BigDecimal fee3Tax,
        String fee3TaxDisplay,
        BigDecimal stampDuty,
        String stampDutyDisplay,
        BigDecimal shouldStampDuty,
        String shouldStampDutyDisplay,
        BigDecimal reductionAmount,
        String reductionAmountDisplay,
        BigDecimal reductionPrincipal,
        String reductionPrincipalDisplay,
        BigDecimal reductionInterest,
        String reductionInterestDisplay,
        BigDecimal reductionFee1,
        String reductionFee1Display,
        BigDecimal reductionFee2,
        String reductionFee2Display,
        BigDecimal reductionFee3,
        String reductionFee3Display,
        BigDecimal reductionFee1Tax,
        String reductionFee1TaxDisplay,
        BigDecimal reductionFee2Tax,
        String reductionFee2TaxDisplay,
        BigDecimal reductionFee3Tax,
        String reductionFee3TaxDisplay,
        BigDecimal reductionStampDuty,
        String reductionStampDutyDisplay
) {
    public static LoanTrialTermResponse from(LoanTrialFacade.TermResult term) {
        return new LoanTrialTermResponse(
                term.termNo(),
                term.termNoDisplay(),
                term.valueDate(),
                term.valueDateDisplay(),
                term.dueDate(),
                term.dueDateDisplay(),
                term.graceDate(),
                term.graceDateDisplay(),
                term.schdAmount(),
                term.schdAmountDisplay(),
                term.schdPrincipal(),
                term.schdPrincipalDisplay(),
                term.showLoanPrincipal(),
                term.showLoanPrincipalDisplay(),
                term.schdInterest(),
                term.schdInterestDisplay(),
                term.showInterest(),
                term.showInterestDisplay(),
                term.shouldAmount(),
                term.shouldAmountDisplay(),
                term.shouldPrincipal(),
                term.shouldPrincipalDisplay(),
                term.shouldInterest(),
                term.shouldInterestDisplay(),
                term.fee1(),
                term.fee1Display(),
                term.fee2(),
                term.fee2Display(),
                term.fee3(),
                term.fee3Display(),
                term.fee1Tax(),
                term.fee1TaxDisplay(),
                term.fee2Tax(),
                term.fee2TaxDisplay(),
                term.fee3Tax(),
                term.fee3TaxDisplay(),
                term.stampDuty(),
                term.stampDutyDisplay(),
                term.shouldStampDuty(),
                term.shouldStampDutyDisplay(),
                term.reductionAmount(),
                term.reductionAmountDisplay(),
                term.reductionPrincipal(),
                term.reductionPrincipalDisplay(),
                term.reductionInterest(),
                term.reductionInterestDisplay(),
                term.reductionFee1(),
                term.reductionFee1Display(),
                term.reductionFee2(),
                term.reductionFee2Display(),
                term.reductionFee3(),
                term.reductionFee3Display(),
                term.reductionFee1Tax(),
                term.reductionFee1TaxDisplay(),
                term.reductionFee2Tax(),
                term.reductionFee2TaxDisplay(),
                term.reductionFee3Tax(),
                term.reductionFee3TaxDisplay(),
                term.reductionStampDuty(),
                term.reductionStampDutyDisplay()
        );
    }
}
