package com.pk.infra.callback.repository;

import com.pk.core.callback.port.AppsFlyerCallbackRepository.AppsFlyerCallbackInsert;

/** Mutable row for MyBatis insert (generated id). */
public class AppsFlyerCallbackInsertParam {
    public Long id;
    public Long userId;
    public String deviceNo;
    public String appsflyerId;
    public String advertisingId;
    public String androidId;
    public String attributedTouchTime;
    public String gpClickTime;
    public String installTime;
    public String mediaSource;
    public String afPrt;
    public String afAdsetId;
    public String afAdset;
    public String afSiteid;
    public String afCId;
    public String campaign;
    public String appVersion;
    public String appId;
    public String deviceType;
    public String osVersion;
    public String countryCode;
    public String city;
    public String postalCode;
    public String ip;
    public String operator;
    public String deviceCategory;
    public String platform;
    public String deviceModel;
    public String idfv;
    public String idfa;
    public String afAd;
    public String afChannel;
    public String attributedTouchType;
    public String afAdId;
    public String afAdType;
    public String contributor1TouchType;
    public String contributor1TouchTime;
    public String contributor1AfPrt;
    public String contributor1MatchType;
    public String contributor1EngagementType;
    public String bundleId;
    public String matchType;
    public String gpInstallBegin;
    public String eventName;
    public String eventType;
    public String customerUserId;
    public String rawData;
    public String callbackStatus;
    public String errorMessage;

    public static AppsFlyerCallbackInsertParam from(AppsFlyerCallbackInsert insert) {
        AppsFlyerCallbackInsertParam p = new AppsFlyerCallbackInsertParam();
        p.userId = insert.userId();
        p.deviceNo = insert.deviceNo();
        p.appsflyerId = insert.appsflyerId();
        p.advertisingId = insert.advertisingId();
        p.androidId = insert.androidId();
        p.attributedTouchTime = insert.attributedTouchTime();
        p.gpClickTime = insert.gpClickTime();
        p.installTime = insert.installTime();
        p.mediaSource = insert.mediaSource();
        p.afPrt = insert.afPrt();
        p.afAdsetId = insert.afAdsetId();
        p.afAdset = insert.afAdset();
        p.afSiteid = insert.afSiteid();
        p.afCId = insert.afCId();
        p.campaign = insert.campaign();
        p.appVersion = insert.appVersion();
        p.appId = insert.appId();
        p.deviceType = insert.deviceType();
        p.osVersion = insert.osVersion();
        p.countryCode = insert.countryCode();
        p.city = insert.city();
        p.postalCode = insert.postalCode();
        p.ip = insert.ip();
        p.operator = insert.operator();
        p.deviceCategory = insert.deviceCategory();
        p.platform = insert.platform();
        p.deviceModel = insert.deviceModel();
        p.idfv = insert.idfv();
        p.idfa = insert.idfa();
        p.afAd = insert.afAd();
        p.afChannel = insert.afChannel();
        p.attributedTouchType = insert.attributedTouchType();
        p.afAdId = insert.afAdId();
        p.afAdType = insert.afAdType();
        p.contributor1TouchType = insert.contributor1TouchType();
        p.contributor1TouchTime = insert.contributor1TouchTime();
        p.contributor1AfPrt = insert.contributor1AfPrt();
        p.contributor1MatchType = insert.contributor1MatchType();
        p.contributor1EngagementType = insert.contributor1EngagementType();
        p.bundleId = insert.bundleId();
        p.matchType = insert.matchType();
        p.gpInstallBegin = insert.gpInstallBegin();
        p.eventName = insert.eventName();
        p.eventType = insert.eventType();
        p.customerUserId = insert.customerUserId();
        p.rawData = insert.rawData();
        p.callbackStatus = insert.callbackStatus();
        p.errorMessage = insert.errorMessage();
        return p;
    }
}
