spring:
  application:
    name: pk-app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${PK_APP_PORT:8080}

pk:
  environment: ${SPRING_PROFILES_ACTIVE:local}
