-- Repayment trial: one dedicated column per lender field (run once per environment).
-- Mirrors loan_quote / loan_quote_term detail storage style.

ALTER TABLE repayment_trial_snapshot
    ADD COLUMN total_paid_amount DECIMAL(18,2) NULL COMMENT 'Total paid amount' AFTER total_reduction_amount,
    ADD COLUMN default_va_no VARCHAR(128) NULL COMMENT 'Default VA number' AFTER total_paid_amount,
    ADD COLUMN default_va_bank_code VARCHAR(32) NULL COMMENT 'Default VA bank code' AFTER default_va_no,
    ADD COLUMN default_va_bank_name VARCHAR(128) NULL COMMENT 'Default VA bank name' AFTER default_va_bank_code,
    ADD COLUMN default_va_bank_type INT NULL COMMENT 'Default VA bank type' AFTER default_va_bank_name,
    ADD COLUMN default_va_icon VARCHAR(512) NULL COMMENT 'Default VA icon URL' AFTER default_va_bank_type,
    ADD COLUMN default_va_default_flag TINYINT(1) NULL COMMENT 'Default VA default flag' AFTER default_va_icon,
    ADD COLUMN default_va_disabled TINYINT(1) NULL COMMENT 'Default VA disabled flag' AFTER default_va_default_flag,
    ADD COLUMN default_va_show TINYINT(1) NULL COMMENT 'Default VA show flag' AFTER default_va_disabled,
    ADD COLUMN spare_va_no VARCHAR(128) NULL COMMENT 'Spare VA number' AFTER default_va_show,
    ADD COLUMN spare_va_bank_code VARCHAR(32) NULL COMMENT 'Spare VA bank code' AFTER spare_va_no,
    ADD COLUMN spare_va_bank_name VARCHAR(128) NULL COMMENT 'Spare VA bank name' AFTER spare_va_bank_code,
    ADD COLUMN spare_va_bank_type INT NULL COMMENT 'Spare VA bank type' AFTER spare_va_bank_name,
    ADD COLUMN spare_va_icon VARCHAR(512) NULL COMMENT 'Spare VA icon URL' AFTER spare_va_bank_type,
    ADD COLUMN spare_va_default_flag TINYINT(1) NULL COMMENT 'Spare VA default flag' AFTER spare_va_icon,
    ADD COLUMN spare_va_disabled TINYINT(1) NULL COMMENT 'Spare VA disabled flag' AFTER spare_va_default_flag,
    ADD COLUMN spare_va_show TINYINT(1) NULL COMMENT 'Spare VA show flag' AFTER spare_va_disabled,
    ADD COLUMN disabled_default_va_no VARCHAR(128) NULL COMMENT 'Disabled default VA number' AFTER spare_va_show,
    ADD COLUMN disabled_default_va_bank_code VARCHAR(32) NULL COMMENT 'Disabled default VA bank code' AFTER disabled_default_va_no,
    ADD COLUMN disabled_default_va_bank_name VARCHAR(128) NULL COMMENT 'Disabled default VA bank name' AFTER disabled_default_va_bank_code,
    ADD COLUMN disabled_default_va_bank_type INT NULL COMMENT 'Disabled default VA bank type' AFTER disabled_default_va_bank_name,
    ADD COLUMN disabled_default_va_icon VARCHAR(512) NULL COMMENT 'Disabled default VA icon URL' AFTER disabled_default_va_bank_type,
    ADD COLUMN disabled_default_va_default_flag TINYINT(1) NULL COMMENT 'Disabled default VA default flag' AFTER disabled_default_va_icon,
    ADD COLUMN disabled_default_va_disabled TINYINT(1) NULL COMMENT 'Disabled default VA disabled flag' AFTER disabled_default_va_default_flag,
    ADD COLUMN disabled_default_va_show TINYINT(1) NULL COMMENT 'Disabled default VA show flag' AFTER disabled_default_va_disabled;

ALTER TABLE repayment_trial_order
    ADD COLUMN loan_apply_no VARCHAR(64) NULL COMMENT 'Lender loan apply number' AFTER loan_apply_id,
    ADD COLUMN bill_no VARCHAR(64) NULL COMMENT 'Bill number' AFTER loan_apply_no,
    ADD COLUMN name VARCHAR(128) NULL COMMENT 'User name' AFTER bill_status,
    ADD COLUMN user_id VARCHAR(64) NULL COMMENT 'Lender user ID' AFTER name,
    ADD COLUMN adv_sette_flag VARCHAR(16) NULL COMMENT 'Early settle flag' AFTER user_id,
    ADD COLUMN currency VARCHAR(16) NULL COMMENT 'Currency' AFTER adv_sette_flag,
    ADD COLUMN apply_amt DECIMAL(18,2) NULL COMMENT 'Apply amount' AFTER currency,
    ADD COLUMN apply_time DATETIME(3) NULL COMMENT 'Apply time' AFTER apply_amt,
    ADD COLUMN audit_time DATETIME(3) NULL COMMENT 'Audit time' AFTER apply_time,
    ADD COLUMN loan_time DATETIME(3) NULL COMMENT 'Loan time' AFTER audit_time,
    ADD COLUMN loan_days INT NULL COMMENT 'Loan days' AFTER loan_time,
    ADD COLUMN repay_method_type INT NULL COMMENT 'Repay method type' AFTER loan_days,
    ADD COLUMN schd_amount DECIMAL(18,2) NULL COMMENT 'Scheduled amount' AFTER repay_method_type,
    ADD COLUMN schd_stamp_duty DECIMAL(18,2) NULL COMMENT 'Scheduled stamp duty' AFTER schd_amount,
    ADD COLUMN schd_principal DECIMAL(18,2) NULL COMMENT 'Scheduled principal' AFTER schd_stamp_duty,
    ADD COLUMN schd_interest DECIMAL(18,2) NULL COMMENT 'Scheduled interest' AFTER schd_principal,
    ADD COLUMN schd_fee1 DECIMAL(18,2) NULL COMMENT 'Scheduled fee1' AFTER schd_interest,
    ADD COLUMN schd_fee2 DECIMAL(18,2) NULL COMMENT 'Scheduled fee2' AFTER schd_fee1,
    ADD COLUMN schd_fee3 DECIMAL(18,2) NULL COMMENT 'Scheduled fee3' AFTER schd_fee2,
    ADD COLUMN schd_fee1_tax DECIMAL(18,2) NULL COMMENT 'Scheduled fee1 tax' AFTER schd_fee3,
    ADD COLUMN schd_fee2_tax DECIMAL(18,2) NULL COMMENT 'Scheduled fee2 tax' AFTER schd_fee1_tax,
    ADD COLUMN schd_fee3_tax DECIMAL(18,2) NULL COMMENT 'Scheduled fee3 tax' AFTER schd_fee2_tax,
    ADD COLUMN pre_pen_interest DECIMAL(18,2) NULL COMMENT 'Pre penalty interest' AFTER schd_fee3_tax,
    ADD COLUMN pen_interest DECIMAL(18,2) NULL COMMENT 'Penalty interest' AFTER pre_pen_interest,
    ADD COLUMN init_late_fee DECIMAL(18,2) NULL COMMENT 'Initial late fee' AFTER pen_interest,
    ADD COLUMN should_stamp_duty DECIMAL(18,2) NULL COMMENT 'Stamp duty due' AFTER should_amount,
    ADD COLUMN should_principal DECIMAL(18,2) NULL COMMENT 'Principal due' AFTER should_stamp_duty,
    ADD COLUMN should_interest DECIMAL(18,2) NULL COMMENT 'Interest due' AFTER should_principal,
    ADD COLUMN fee1_name VARCHAR(128) NULL COMMENT 'Fee1 name' AFTER should_interest,
    ADD COLUMN should_fee1 DECIMAL(18,2) NULL COMMENT 'Fee1 due' AFTER fee1_name,
    ADD COLUMN fee2_name VARCHAR(128) NULL COMMENT 'Fee2 name' AFTER should_fee1,
    ADD COLUMN should_fee2 DECIMAL(18,2) NULL COMMENT 'Fee2 due' AFTER fee2_name,
    ADD COLUMN fee3_name VARCHAR(128) NULL COMMENT 'Fee3 name' AFTER should_fee2,
    ADD COLUMN should_fee3 DECIMAL(18,2) NULL COMMENT 'Fee3 due' AFTER fee3_name,
    ADD COLUMN should_fee1_tax DECIMAL(18,2) NULL COMMENT 'Fee1 tax due' AFTER should_fee3,
    ADD COLUMN should_fee2_tax DECIMAL(18,2) NULL COMMENT 'Fee2 tax due' AFTER should_fee1_tax,
    ADD COLUMN should_fee3_tax DECIMAL(18,2) NULL COMMENT 'Fee3 tax due' AFTER should_fee2_tax,
    ADD COLUMN should_fee DECIMAL(18,2) NULL COMMENT 'Fee due total' AFTER should_fee3_tax,
    ADD COLUMN should_pen_interest DECIMAL(18,2) NULL COMMENT 'Penalty interest due' AFTER should_fee,
    ADD COLUMN should_init_late_fee DECIMAL(18,2) NULL COMMENT 'Initial late fee due' AFTER should_pen_interest,
    ADD COLUMN should_adv_settle_fee DECIMAL(18,2) NULL COMMENT 'Early settle fee due' AFTER should_init_late_fee,
    ADD COLUMN should_penalty DECIMAL(18,2) NULL COMMENT 'Penalty due total' AFTER should_adv_settle_fee,
    ADD COLUMN reduction_amount DECIMAL(18,2) NULL COMMENT 'Reduction amount' AFTER should_penalty,
    ADD COLUMN reduction_stamp_duty DECIMAL(18,2) NULL COMMENT 'Reduced stamp duty' AFTER reduction_amount,
    ADD COLUMN reduction_principal DECIMAL(18,2) NULL COMMENT 'Reduced principal' AFTER reduction_stamp_duty,
    ADD COLUMN reduction_interest DECIMAL(18,2) NULL COMMENT 'Reduced interest' AFTER reduction_principal,
    ADD COLUMN reduction_fee1 DECIMAL(18,2) NULL COMMENT 'Reduced fee1' AFTER reduction_interest,
    ADD COLUMN reduction_fee2 DECIMAL(18,2) NULL COMMENT 'Reduced fee2' AFTER reduction_fee1,
    ADD COLUMN reduction_fee3 DECIMAL(18,2) NULL COMMENT 'Reduced fee3' AFTER reduction_fee2,
    ADD COLUMN reduction_fee1_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee1 tax' AFTER reduction_fee3,
    ADD COLUMN reduction_fee2_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee2 tax' AFTER reduction_fee1_tax,
    ADD COLUMN reduction_fee3_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee3 tax' AFTER reduction_fee2_tax,
    ADD COLUMN reduction_pen_interest DECIMAL(18,2) NULL COMMENT 'Reduced penalty interest' AFTER reduction_fee3_tax,
    ADD COLUMN reduction_init_late_fee DECIMAL(18,2) NULL COMMENT 'Reduced initial late fee' AFTER reduction_pen_interest,
    ADD COLUMN coupon_amount DECIMAL(18,2) NULL COMMENT 'Coupon amount' AFTER reduction_init_late_fee,
    ADD COLUMN part_repay_flag VARCHAR(16) NULL COMMENT 'Partial repay flag' AFTER coupon_amount,
    ADD COLUMN paid_amount DECIMAL(18,2) NULL COMMENT 'Paid amount' AFTER part_repay_flag,
    ADD COLUMN coupon_id BIGINT NULL COMMENT 'Coupon ID' AFTER paid_amount,
    ADD COLUMN coupon_type VARCHAR(64) NULL COMMENT 'Coupon type' AFTER coupon_id,
    ADD COLUMN coupon_name VARCHAR(128) NULL COMMENT 'Coupon name' AFTER coupon_type,
    ADD COLUMN user_valide_dis_time BIGINT NULL COMMENT 'Coupon validity countdown ms' AFTER coupon_name,
    ADD COLUMN term_no INT NULL COMMENT 'Nearest repay term' AFTER user_valide_dis_time,
    ADD COLUMN term_due_date DATETIME(3) NULL COMMENT 'Nearest repay due date' AFTER term_no,
    ADD COLUMN default_va_no VARCHAR(128) NULL COMMENT 'Default VA number' AFTER term_due_date,
    ADD COLUMN default_va_bank_code VARCHAR(32) NULL COMMENT 'Default VA bank code' AFTER default_va_no,
    ADD COLUMN default_va_bank_name VARCHAR(128) NULL COMMENT 'Default VA bank name' AFTER default_va_bank_code,
    ADD COLUMN default_va_bank_type INT NULL COMMENT 'Default VA bank type' AFTER default_va_bank_name,
    ADD COLUMN default_va_icon VARCHAR(512) NULL COMMENT 'Default VA icon URL' AFTER default_va_bank_type,
    ADD COLUMN default_va_default_flag TINYINT(1) NULL COMMENT 'Default VA default flag' AFTER default_va_icon,
    ADD COLUMN default_va_disabled TINYINT(1) NULL COMMENT 'Default VA disabled flag' AFTER default_va_default_flag,
    ADD COLUMN default_va_show TINYINT(1) NULL COMMENT 'Default VA show flag' AFTER default_va_disabled,
    ADD COLUMN spare_va_no VARCHAR(128) NULL COMMENT 'Spare VA number' AFTER default_va_show,
    ADD COLUMN spare_va_bank_code VARCHAR(32) NULL COMMENT 'Spare VA bank code' AFTER spare_va_no,
    ADD COLUMN spare_va_bank_name VARCHAR(128) NULL COMMENT 'Spare VA bank name' AFTER spare_va_bank_code,
    ADD COLUMN spare_va_bank_type INT NULL COMMENT 'Spare VA bank type' AFTER spare_va_bank_name,
    ADD COLUMN spare_va_icon VARCHAR(512) NULL COMMENT 'Spare VA icon URL' AFTER spare_va_bank_type,
    ADD COLUMN spare_va_default_flag TINYINT(1) NULL COMMENT 'Spare VA default flag' AFTER spare_va_icon,
    ADD COLUMN spare_va_disabled TINYINT(1) NULL COMMENT 'Spare VA disabled flag' AFTER spare_va_default_flag,
    ADD COLUMN spare_va_show TINYINT(1) NULL COMMENT 'Spare VA show flag' AFTER spare_va_disabled,
    ADD COLUMN disabled_default_va_no VARCHAR(128) NULL COMMENT 'Disabled default VA number' AFTER spare_va_show,
    ADD COLUMN disabled_default_va_bank_code VARCHAR(32) NULL COMMENT 'Disabled default VA bank code' AFTER disabled_default_va_no,
    ADD COLUMN disabled_default_va_bank_name VARCHAR(128) NULL COMMENT 'Disabled default VA bank name' AFTER disabled_default_va_bank_code,
    ADD COLUMN disabled_default_va_bank_type INT NULL COMMENT 'Disabled default VA bank type' AFTER disabled_default_va_bank_name,
    ADD COLUMN disabled_default_va_icon VARCHAR(512) NULL COMMENT 'Disabled default VA icon URL' AFTER disabled_default_va_bank_type,
    ADD COLUMN disabled_default_va_default_flag TINYINT(1) NULL COMMENT 'Disabled default VA default flag' AFTER disabled_default_va_icon,
    ADD COLUMN disabled_default_va_disabled TINYINT(1) NULL COMMENT 'Disabled default VA disabled flag' AFTER disabled_default_va_default_flag,
    ADD COLUMN disabled_default_va_show TINYINT(1) NULL COMMENT 'Disabled default VA show flag' AFTER disabled_default_va_disabled;

CREATE TABLE IF NOT EXISTS repayment_trial_term (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    trial_order_id BIGINT UNSIGNED NOT NULL COMMENT 'Repayment trial order identifier',
    bill_no VARCHAR(64) NULL COMMENT 'Bill number',
    loan_apply_no VARCHAR(64) NULL COMMENT 'Loan apply number',
    term_no INT NOT NULL COMMENT 'Term number',
    adv_sette_flag VARCHAR(16) NULL COMMENT 'Early settle flag',
    schd_amount DECIMAL(18,2) NULL COMMENT 'Scheduled amount',
    schd_stamp_duty DECIMAL(18,2) NULL COMMENT 'Scheduled stamp duty',
    schd_principal DECIMAL(18,2) NULL COMMENT 'Scheduled principal',
    schd_interest DECIMAL(18,2) NULL COMMENT 'Scheduled interest',
    schd_all_fee DECIMAL(18,2) NULL COMMENT 'Scheduled all fee',
    schd_all_tax_fee DECIMAL(18,2) NULL COMMENT 'Scheduled all tax fee',
    schd_fee1 DECIMAL(18,2) NULL COMMENT 'Scheduled fee1',
    schd_fee2 DECIMAL(18,2) NULL COMMENT 'Scheduled fee2',
    schd_fee3 DECIMAL(18,2) NULL COMMENT 'Scheduled fee3',
    schd_fee1_tax DECIMAL(18,2) NULL COMMENT 'Scheduled fee1 tax',
    schd_fee2_tax DECIMAL(18,2) NULL COMMENT 'Scheduled fee2 tax',
    schd_fee3_tax DECIMAL(18,2) NULL COMMENT 'Scheduled fee3 tax',
    pre_pen_interest DECIMAL(18,2) NULL COMMENT 'Pre penalty interest',
    pen_interest DECIMAL(18,2) NULL COMMENT 'Penalty interest',
    init_late_fee DECIMAL(18,2) NULL COMMENT 'Initial late fee',
    due_date DATETIME(3) NULL COMMENT 'Due date',
    overdue_days INT NULL COMMENT 'Overdue days',
    grace_date DATETIME(3) NULL COMMENT 'Grace date',
    term_status VARCHAR(32) NULL COMMENT 'Term status',
    days_of_due_date BIGINT NULL COMMENT 'Days of due date',
    should_amount DECIMAL(18,2) NULL COMMENT 'Amount due',
    should_stamp_duty DECIMAL(18,2) NULL COMMENT 'Stamp duty due',
    should_principal DECIMAL(18,2) NULL COMMENT 'Principal due',
    should_interest DECIMAL(18,2) NULL COMMENT 'Interest due',
    should_fee1 DECIMAL(18,2) NULL COMMENT 'Fee1 due',
    should_fee2 DECIMAL(18,2) NULL COMMENT 'Fee2 due',
    should_fee3 DECIMAL(18,2) NULL COMMENT 'Fee3 due',
    should_fee1_tax DECIMAL(18,2) NULL COMMENT 'Fee1 tax due',
    should_fee2_tax DECIMAL(18,2) NULL COMMENT 'Fee2 tax due',
    should_fee3_tax DECIMAL(18,2) NULL COMMENT 'Fee3 tax due',
    should_pen_interest DECIMAL(18,2) NULL COMMENT 'Penalty interest due',
    should_init_late_fee DECIMAL(18,2) NULL COMMENT 'Initial late fee due',
    part_repay_flag VARCHAR(16) NULL COMMENT 'Partial repay flag',
    paid_amount DECIMAL(18,2) NULL COMMENT 'Paid amount',
    coupon_discount DECIMAL(18,2) NULL COMMENT 'Coupon discount',
    reduction_amount DECIMAL(18,2) NULL COMMENT 'Reduction amount',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Record creation time',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Record update time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_repayment_trial_term (trial_order_id, term_no),
    KEY idx_repayment_trial_term_order (trial_order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Repayment trial term details';

CREATE TABLE IF NOT EXISTS repayment_trial_term_discount (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    trial_term_id BIGINT UNSIGNED NOT NULL COMMENT 'Repayment trial term identifier',
    reduction_all_amt DECIMAL(18,2) NULL COMMENT 'Reduction all amount',
    reduction_type VARCHAR(64) NULL COMMENT 'Reduction type',
    reduction_stamp_duty DECIMAL(18,2) NULL COMMENT 'Reduced stamp duty',
    reduction_principal DECIMAL(18,2) NULL COMMENT 'Reduced principal',
    reduction_interest DECIMAL(18,2) NULL COMMENT 'Reduced interest',
    reduction_fee1 DECIMAL(18,2) NULL COMMENT 'Reduced fee1',
    reduction_fee2 DECIMAL(18,2) NULL COMMENT 'Reduced fee2',
    reduction_fee3 DECIMAL(18,2) NULL COMMENT 'Reduced fee3',
    reduction_fee1_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee1 tax',
    reduction_fee2_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee2 tax',
    reduction_fee3_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee3 tax',
    reduction_pen_interest DECIMAL(18,2) NULL COMMENT 'Reduced penalty interest',
    reduction_init_late_fee DECIMAL(18,2) NULL COMMENT 'Reduced initial late fee',
    coupon_id BIGINT NULL COMMENT 'Coupon ID',
    coupon_type VARCHAR(64) NULL COMMENT 'Coupon type',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Record creation time',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Record update time',
    PRIMARY KEY (id),
    KEY idx_repayment_trial_term_discount_term (trial_term_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Repayment trial term discount details';

CREATE TABLE IF NOT EXISTS repayment_trial_va_channel (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    owner_type VARCHAR(32) NOT NULL COMMENT 'SNAPSHOT or ORDER',
    owner_id BIGINT UNSIGNED NOT NULL COMMENT 'Snapshot id or order id',
    va_role VARCHAR(32) NOT NULL COMMENT 'DEFAULT / SPARE / DISABLED_DEFAULT',
    bank_channel VARCHAR(64) NULL COMMENT 'Bank channel',
    instruction VARCHAR(1024) NULL COMMENT 'Channel instruction',
    default_channel TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Default channel flag',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Record creation time',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Record update time',
    PRIMARY KEY (id),
    KEY idx_repayment_trial_va_channel_owner (owner_type, owner_id, va_role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Repayment trial VA bank channels';

ALTER TABLE repayment_trial_snapshot DROP COLUMN IF EXISTS default_va_json;
ALTER TABLE repayment_trial_order DROP COLUMN IF EXISTS term_info_json;
