-- Loan trial: one dedicated column per lender field (run once per environment).

ALTER TABLE loan_quote
    ADD COLUMN apply_id VARCHAR(64) NULL COMMENT 'Lender credit apply ID' AFTER product_snapshot_id,
    ADD COLUMN credit_apply_no VARCHAR(64) NULL COMMENT 'Lender credit apply number' AFTER apply_id,
    ADD COLUMN user_id VARCHAR(64) NULL COMMENT 'Lender user ID' AFTER credit_apply_no,
    ADD COLUMN loan_term INT NULL COMMENT 'Loan term count' AFTER apply_amt,
    ADD COLUMN show_loan_principal DECIMAL(18,2) NULL COMMENT 'Displayed loan principal' AFTER loan_principal,
    ADD COLUMN hand_fee DECIMAL(18,2) NULL COMMENT 'Upfront fee amount' AFTER pay_amount,
    ADD COLUMN should_amount DECIMAL(18,2) NULL COMMENT 'Total amount due after coupon' AFTER schd_amount,
    ADD COLUMN day_rate DECIMAL(18,6) NULL COMMENT 'Daily interest rate' AFTER interest,
    ADD COLUMN show_day_rate DECIMAL(18,6) NULL COMMENT 'Displayed daily interest rate' AFTER day_rate,
    ADD COLUMN fee1_name VARCHAR(128) NULL COMMENT 'Fee 1 name' AFTER total_days,
    ADD COLUMN fee1 DECIMAL(18,2) NULL COMMENT 'Fee 1 amount' AFTER fee1_name,
    ADD COLUMN fee2_name VARCHAR(128) NULL COMMENT 'Fee 2 name' AFTER fee1,
    ADD COLUMN fee2 DECIMAL(18,2) NULL COMMENT 'Fee 2 amount' AFTER fee2_name,
    ADD COLUMN fee3_name VARCHAR(128) NULL COMMENT 'Fee 3 name' AFTER fee2,
    ADD COLUMN fee3 DECIMAL(18,2) NULL COMMENT 'Fee 3 amount' AFTER fee3_name,
    ADD COLUMN tax DECIMAL(18,2) NULL COMMENT 'Tax amount' AFTER fee3,
    ADD COLUMN tax_rate_percent VARCHAR(32) NULL COMMENT 'Tax rate display' AFTER tax,
    ADD COLUMN ppn_amount DECIMAL(18,2) NULL COMMENT 'PPN amount' AFTER tax_rate_percent,
    ADD COLUMN should_stamp_duty DECIMAL(18,2) NULL COMMENT 'Stamp duty due' AFTER ppn_amount,
    ADD COLUMN should_principal DECIMAL(18,2) NULL COMMENT 'Principal due' AFTER should_stamp_duty,
    ADD COLUMN should_interest DECIMAL(18,2) NULL COMMENT 'Interest due' AFTER should_principal,
    ADD COLUMN should_fee1 DECIMAL(18,2) NULL COMMENT 'Fee 1 due' AFTER should_interest,
    ADD COLUMN should_fee2 DECIMAL(18,2) NULL COMMENT 'Fee 2 due' AFTER should_fee1,
    ADD COLUMN should_fee3 DECIMAL(18,2) NULL COMMENT 'Fee 3 due' AFTER should_fee2,
    ADD COLUMN should_fee1_tax DECIMAL(18,2) NULL COMMENT 'Fee 1 tax due' AFTER should_fee3,
    ADD COLUMN should_fee2_tax DECIMAL(18,2) NULL COMMENT 'Fee 2 tax due' AFTER should_fee1_tax,
    ADD COLUMN should_fee3_tax DECIMAL(18,2) NULL COMMENT 'Fee 3 tax due' AFTER should_fee2_tax,
    ADD COLUMN reduction_amount DECIMAL(18,2) NULL COMMENT 'Total reduction amount' AFTER should_fee3_tax,
    ADD COLUMN ad_reduction_amt DECIMAL(18,2) NULL COMMENT 'Early settlement reduction amount' AFTER reduction_amount,
    ADD COLUMN ad_reduction_ratio DECIMAL(18,6) NULL COMMENT 'Early settlement reduction ratio' AFTER ad_reduction_amt,
    ADD COLUMN ad_reduction_end_date BIGINT NULL COMMENT 'Early settlement reduction end time (epoch millis)' AFTER ad_reduction_ratio,
    ADD COLUMN reduction_stamp_duty DECIMAL(18,2) NULL COMMENT 'Reduced stamp duty' AFTER ad_reduction_end_date,
    ADD COLUMN reduction_principal DECIMAL(18,2) NULL COMMENT 'Reduced principal' AFTER reduction_stamp_duty,
    ADD COLUMN reduction_interest DECIMAL(18,2) NULL COMMENT 'Reduced interest' AFTER reduction_principal,
    ADD COLUMN reduction_fee1 DECIMAL(18,2) NULL COMMENT 'Reduced fee 1' AFTER reduction_interest,
    ADD COLUMN reduction_fee2 DECIMAL(18,2) NULL COMMENT 'Reduced fee 2' AFTER reduction_fee1,
    ADD COLUMN reduction_fee3 DECIMAL(18,2) NULL COMMENT 'Reduced fee 3' AFTER reduction_fee2,
    ADD COLUMN reduction_fee1_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee 1 tax' AFTER reduction_fee3,
    ADD COLUMN reduction_fee2_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee 2 tax' AFTER reduction_fee1_tax,
    ADD COLUMN reduction_fee3_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee 3 tax' AFTER reduction_fee2_tax,
    ADD COLUMN after_service_fee_status VARCHAR(16) NULL COMMENT 'Post-service fee status' AFTER reduction_fee3_tax,
    ADD COLUMN fee_prepay_type INT NULL COMMENT 'Upfront fee type' AFTER after_service_fee_status,
    ADD COLUMN lending_date BIGINT NULL COMMENT 'Disbursement date (epoch millis)' AFTER fee_prepay_type,
    ADD COLUMN first_repay_date BIGINT NULL COMMENT 'First repayment date (epoch millis)' AFTER lending_date,
    ADD COLUMN last_repay_date BIGINT NULL COMMENT 'Last repayment date (epoch millis)' AFTER first_repay_date,
    ADD COLUMN uneven_bills_flag TINYINT(1) NULL COMMENT 'Uneven bills flag' AFTER last_repay_date;

ALTER TABLE loan_quote_term
    ADD COLUMN value_date DATETIME(3) NULL COMMENT 'Value date' AFTER term_no,
    ADD COLUMN grace_date DATETIME(3) NULL COMMENT 'Grace date' AFTER due_date,
    ADD COLUMN show_loan_principal DECIMAL(18,2) NULL COMMENT 'Displayed loan principal' AFTER schd_principal,
    ADD COLUMN show_interest DECIMAL(18,2) NULL COMMENT 'Displayed interest' AFTER schd_interest,
    ADD COLUMN should_amount DECIMAL(18,2) NULL COMMENT 'Total amount due' AFTER show_interest,
    ADD COLUMN should_principal DECIMAL(18,2) NULL COMMENT 'Principal due' AFTER should_amount,
    ADD COLUMN should_interest DECIMAL(18,2) NULL COMMENT 'Interest due' AFTER should_principal,
    ADD COLUMN fee1 DECIMAL(18,2) NULL COMMENT 'Fee 1 amount' AFTER should_interest,
    ADD COLUMN fee2 DECIMAL(18,2) NULL COMMENT 'Fee 2 amount' AFTER fee1,
    ADD COLUMN fee3 DECIMAL(18,2) NULL COMMENT 'Fee 3 amount' AFTER fee2,
    ADD COLUMN fee1_tax DECIMAL(18,2) NULL COMMENT 'Fee 1 tax' AFTER fee3,
    ADD COLUMN fee2_tax DECIMAL(18,2) NULL COMMENT 'Fee 2 tax' AFTER fee1_tax,
    ADD COLUMN fee3_tax DECIMAL(18,2) NULL COMMENT 'Fee 3 tax' AFTER fee2_tax,
    ADD COLUMN stamp_duty DECIMAL(18,2) NULL COMMENT 'Stamp duty' AFTER fee3_tax,
    ADD COLUMN should_stamp_duty DECIMAL(18,2) NULL COMMENT 'Stamp duty due' AFTER stamp_duty,
    ADD COLUMN reduction_amount DECIMAL(18,2) NULL COMMENT 'Reduction amount' AFTER should_stamp_duty,
    ADD COLUMN reduction_principal DECIMAL(18,2) NULL COMMENT 'Reduced principal' AFTER reduction_amount,
    ADD COLUMN reduction_interest DECIMAL(18,2) NULL COMMENT 'Reduced interest' AFTER reduction_principal,
    ADD COLUMN reduction_fee1 DECIMAL(18,2) NULL COMMENT 'Reduced fee 1' AFTER reduction_interest,
    ADD COLUMN reduction_fee2 DECIMAL(18,2) NULL COMMENT 'Reduced fee 2' AFTER reduction_fee1,
    ADD COLUMN reduction_fee3 DECIMAL(18,2) NULL COMMENT 'Reduced fee 3' AFTER reduction_fee2,
    ADD COLUMN reduction_fee1_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee 1 tax' AFTER reduction_fee3,
    ADD COLUMN reduction_fee2_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee 2 tax' AFTER reduction_fee1_tax,
    ADD COLUMN reduction_fee3_tax DECIMAL(18,2) NULL COMMENT 'Reduced fee 3 tax' AFTER reduction_fee2_tax,
    ADD COLUMN reduction_stamp_duty DECIMAL(18,2) NULL COMMENT 'Reduced stamp duty' AFTER reduction_fee3_tax;

ALTER TABLE loan_quote DROP COLUMN IF EXISTS trial_detail_json;
ALTER TABLE loan_quote DROP COLUMN IF EXISTS fee_json;
ALTER TABLE loan_quote_term DROP COLUMN IF EXISTS term_detail_json;
ALTER TABLE loan_quote_term DROP COLUMN IF EXISTS fee_json;
