-- Create user_device_other_info for documented deviceOtherInfo fields + JSON.
-- Compatible with MySQL 5.7 / 8.0. Safe to re-run.

CREATE TABLE IF NOT EXISTS user_device_other_info (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    profile_id BIGINT UNSIGNED NOT NULL COMMENT 'User profile identifier',
    partner_user_id VARCHAR(64) NOT NULL COMMENT 'Partner user identifier',
    device_no VARCHAR(128) NOT NULL COMMENT 'Device identifier (upsert key)',
    allow_mock_location TINYINT(1) NULL COMMENT 'allowMockLocation',
    app_sign VARCHAR(128) NULL COMMENT 'appSign',
    baseband_version VARCHAR(128) NULL COMMENT 'basebandVersion',
    battery VARCHAR(32) NULL COMMENT 'battery',
    battery_temp INT NULL COMMENT 'batteryTemp',
    brand VARCHAR(64) NULL COMMENT 'brand',
    brightness INT NULL COMMENT 'brightness',
    camera_num VARCHAR(16) NULL COMMENT 'cameraNum',
    cpu_hardware VARCHAR(64) NULL COMMENT 'cpuHardware',
    dbm INT NULL COMMENT 'dbm',
    disk_free_space VARCHAR(32) NULL COMMENT 'diskFreeSpace',
    disk_space VARCHAR(32) NULL COMMENT 'diskSpace',
    finger_print VARCHAR(512) NULL COMMENT 'fingerPrint',
    free_memory VARCHAR(32) NULL COMMENT 'freeMemory',
    gaid VARCHAR(128) NULL COMMENT 'gaid',
    imsi VARCHAR(64) NULL COMMENT 'imsi',
    is_ac_charge TINYINT(1) NULL COMMENT 'isAcCharge',
    is_charging TINYINT(1) NULL COMMENT 'isCharging',
    is_debug TINYINT(1) NULL COMMENT 'isDebug',
    is_networking_roaming VARCHAR(16) NULL COMMENT 'isNetworkingRoaming',
    is_proxy TINYINT(1) NULL COMMENT 'isProxy',
    is_root TINYINT(1) NULL COMMENT 'isRoot',
    is_simulator TINYINT(1) NULL COMMENT 'isSimulator',
    is_usb_charge TINYINT(1) NULL COMMENT 'isUsbCharge',
    kernel_version VARCHAR(128) NULL COMMENT 'kernelVersion',
    keyboard INT NULL COMMENT 'keyboard',
    last_boot_time BIGINT NULL COMMENT 'lastBootTime',
    local_display_language VARCHAR(64) NULL COMMENT 'localDisplayLanguage',
    local_iso3_country VARCHAR(16) NULL COMMENT 'localIso3Country',
    local_iso3_language VARCHAR(16) NULL COMMENT 'localIso3Language',
    mac_address VARCHAR(64) NULL COMMENT 'macAddress',
    manufacturer VARCHAR(64) NULL COMMENT 'manufacturer',
    model_no VARCHAR(64) NULL COMMENT 'modelNo',
    network_country_iso VARCHAR(16) NULL COMMENT 'networkCountryIso',
    network_operator VARCHAR(64) NULL COMMENT 'networkOperator',
    network_type VARCHAR(64) NULL COMMENT 'networkType',
    os_version VARCHAR(64) NULL COMMENT 'osVersion',
    screen_height VARCHAR(16) NULL COMMENT 'screenHeight',
    screen_width VARCHAR(16) NULL COMMENT 'screenWidth',
    sensor TEXT NULL COMMENT 'sensor',
    serial_no VARCHAR(128) NULL COMMENT 'serialNo',
    sim_country_iso VARCHAR(16) NULL COMMENT 'simCountryIso',
    sim_operator VARCHAR(64) NULL COMMENT 'simOperator',
    sim_operator_name VARCHAR(64) NULL COMMENT 'simOperatorName',
    timezone VARCHAR(64) NULL COMMENT 'timezone',
    total_memory VARCHAR(32) NULL COMMENT 'totalMemory',
    up_time VARCHAR(32) NULL COMMENT 'upTime',
    wifi_bssid VARCHAR(64) NULL COMMENT 'wifiBSSID',
    wifi_rssi VARCHAR(32) NULL COMMENT 'wifiRSSI',
    wifi_ssid VARCHAR(128) NULL COMMENT 'wifiSSID',
    mac VARCHAR(64) NULL COMMENT 'mac',
    net_mode INT NULL COMMENT 'netMode',
    memory_total BIGINT NULL COMMENT 'memoryTotal',
    memory_available BIGINT NULL COMMENT 'memoryAvailable',
    sd_card_total BIGINT NULL COMMENT 'sdCardTotal',
    sd_card_available BIGINT NULL COMMENT 'sdCardAvailable',
    up_time_sec BIGINT NULL COMMENT 'upTimeSec',
    display_metrics VARCHAR(128) NULL COMMENT 'displayMetrics',
    cpu_cores INT NULL COMMENT 'cpuCores',
    cpu_name VARCHAR(64) NULL COMMENT 'cpuName',
    cpu_max_freq BIGINT NULL COMMENT 'cpuMaxFreq',
    cpu_min_freq BIGINT NULL COMMENT 'cpuMinFreq',
    cpu_cur_freq BIGINT NULL COMMENT 'cpuCurFreq',
    device_other_info_json JSON NOT NULL COMMENT 'Filtered deviceOtherInfo JSON (document fields only)',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Record creation time',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Record update time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_device_other_info_device_no (device_no),
    KEY idx_user_device_other_info_profile_id (profile_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Documented deviceOtherInfo columns plus JSON snapshot';
