package com.pk.app.repay.dto.response;

import com.pk.core.display.DisplayFormatters;
import com.pk.core.repay.LenderRepayTrialResult;
import com.pk.infra.repay.RepayTrialFacade;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public record RepayTrialResponse(
        String trialNo,
        long expiresAt,
        String loanApplyId,
        String loanApplyNo,
        String billNo,
        String billStatus,
        String name,
        String userId,
        String advSetteFlag,
        String currency,
        BigDecimal applyAmt,
        String applyAmtDisplay,
        Long applyTime,
        Long auditTime,
        Long loanTime,
        Integer loanDays,
        Integer repayMethodType,
        BigDecimal schdAmount,
        String schdAmountDisplay,
        BigDecimal schdStampDuty,
        String schdStampDutyDisplay,
        BigDecimal schdPrincipal,
        String schdPrincipalDisplay,
        BigDecimal schdInterest,
        String schdInterestDisplay,
        BigDecimal schdFee1,
        String schdFee1Display,
        BigDecimal schdFee2,
        String schdFee2Display,
        BigDecimal schdFee3,
        String schdFee3Display,
        BigDecimal schdFee1Tax,
        String schdFee1TaxDisplay,
        BigDecimal schdFee2Tax,
        String schdFee2TaxDisplay,
        BigDecimal schdFee3Tax,
        String schdFee3TaxDisplay,
        BigDecimal prePenInterest,
        String prePenInterestDisplay,
        BigDecimal penInterest,
        String penInterestDisplay,
        BigDecimal initLateFee,
        String initLateFeeDisplay,
        BigDecimal shouldAmount,
        String shouldAmountDisplay,
        BigDecimal shouldStampDuty,
        String shouldStampDutyDisplay,
        BigDecimal shouldPrincipal,
        String shouldPrincipalDisplay,
        BigDecimal shouldInterest,
        String shouldInterestDisplay,
        String fee1Name,
        BigDecimal shouldFee1,
        String shouldFee1Display,
        String fee2Name,
        BigDecimal shouldFee2,
        String shouldFee2Display,
        String fee3Name,
        BigDecimal shouldFee3,
        String shouldFee3Display,
        BigDecimal shouldFee1Tax,
        String shouldFee1TaxDisplay,
        BigDecimal shouldFee2Tax,
        String shouldFee2TaxDisplay,
        BigDecimal shouldFee3Tax,
        String shouldFee3TaxDisplay,
        BigDecimal shouldFee,
        String shouldFeeDisplay,
        BigDecimal shouldPenInterest,
        String shouldPenInterestDisplay,
        BigDecimal shouldInitLateFee,
        String shouldInitLateFeeDisplay,
        BigDecimal shouldAdvSettleFee,
        String shouldAdvSettleFeeDisplay,
        BigDecimal shouldPenalty,
        String shouldPenaltyDisplay,
        BigDecimal reductionAmount,
        String reductionAmountDisplay,
        BigDecimal reductionStampDuty,
        String reductionStampDutyDisplay,
        BigDecimal reductionPrincipal,
        String reductionPrincipalDisplay,
        BigDecimal reductionInterest,
        String reductionInterestDisplay,
        BigDecimal reductionFee1,
        String reductionFee1Display,
        BigDecimal reductionFee2,
        String reductionFee2Display,
        BigDecimal reductionFee3,
        String reductionFee3Display,
        BigDecimal reductionFee1Tax,
        String reductionFee1TaxDisplay,
        BigDecimal reductionFee2Tax,
        String reductionFee2TaxDisplay,
        BigDecimal reductionFee3Tax,
        String reductionFee3TaxDisplay,
        BigDecimal reductionPenInterest,
        String reductionPenInterestDisplay,
        BigDecimal reductionInitLateFee,
        String reductionInitLateFeeDisplay,
        BigDecimal couponAmount,
        String couponAmountDisplay,
        String partRepayFlag,
        BigDecimal paidAmount,
        String paidAmountDisplay,
        RepayTrialVaResponse defaultVa,
        RepayTrialVaResponse spareVa,
        RepayTrialVaResponse disabledDefaultVa,
        Long couponId,
        String couponType,
        String couponName,
        Long userValideDisTime,
        Integer termNo,
        Long termDueDate,
        String termDueDateDisplay,
        List<RepayTrialTermResponse> termInfo
) {
    public static RepayTrialResponse from(RepayTrialFacade.TrialResult result) {
        LenderRepayTrialResult lender = result.lender();
        Long termDueDateMillis = toMillis(lender.termDueDate());
        return new RepayTrialResponse(
                result.trialNo(),
                result.expiresAt(),
                lender.loanApplyId(),
                lender.loanApplyNo(),
                lender.billNo(),
                lender.billStatus(),
                lender.name(),
                lender.userId(),
                lender.advSetteFlag(),
                lender.currency(),
                lender.applyAmt(),
                DisplayFormatters.formatIdrAmount(lender.applyAmt()),
                toMillis(lender.applyTime()),
                toMillis(lender.auditTime()),
                toMillis(lender.loanTime()),
                lender.loanDays(),
                lender.repayMethodType(),
                lender.schdAmount(),
                DisplayFormatters.formatIdrAmount(lender.schdAmount()),
                lender.schdStampDuty(),
                DisplayFormatters.formatIdrAmount(lender.schdStampDuty()),
                lender.schdPrincipal(),
                DisplayFormatters.formatIdrAmount(lender.schdPrincipal()),
                lender.schdInterest(),
                DisplayFormatters.formatIdrAmount(lender.schdInterest()),
                lender.schdFee1(),
                DisplayFormatters.formatIdrAmount(lender.schdFee1()),
                lender.schdFee2(),
                DisplayFormatters.formatIdrAmount(lender.schdFee2()),
                lender.schdFee3(),
                DisplayFormatters.formatIdrAmount(lender.schdFee3()),
                lender.schdFee1Tax(),
                DisplayFormatters.formatIdrAmount(lender.schdFee1Tax()),
                lender.schdFee2Tax(),
                DisplayFormatters.formatIdrAmount(lender.schdFee2Tax()),
                lender.schdFee3Tax(),
                DisplayFormatters.formatIdrAmount(lender.schdFee3Tax()),
                lender.prePenInterest(),
                DisplayFormatters.formatIdrAmount(lender.prePenInterest()),
                lender.penInterest(),
                DisplayFormatters.formatIdrAmount(lender.penInterest()),
                lender.initLateFee(),
                DisplayFormatters.formatIdrAmount(lender.initLateFee()),
                lender.shouldAmount(),
                DisplayFormatters.formatIdrAmount(lender.shouldAmount()),
                lender.shouldStampDuty(),
                DisplayFormatters.formatIdrAmount(lender.shouldStampDuty()),
                lender.shouldPrincipal(),
                DisplayFormatters.formatIdrAmount(lender.shouldPrincipal()),
                lender.shouldInterest(),
                DisplayFormatters.formatIdrAmount(sum(lender.shouldInterest(), lender.shouldFee1())),
                lender.fee1Name(),
                lender.shouldFee1(),
                DisplayFormatters.formatIdrAmount(lender.shouldFee1()),
                lender.fee2Name(),
                lender.shouldFee2(),
                DisplayFormatters.formatIdrAmount(lender.shouldFee2()),
                lender.fee3Name(),
                lender.shouldFee3(),
                DisplayFormatters.formatIdrAmount(lender.shouldFee3()),
                lender.shouldFee1Tax(),
                DisplayFormatters.formatIdrAmount(lender.shouldFee1Tax()),
                lender.shouldFee2Tax(),
                DisplayFormatters.formatIdrAmount(lender.shouldFee2Tax()),
                lender.shouldFee3Tax(),
                DisplayFormatters.formatIdrAmount(lender.shouldFee3Tax()),
                lender.shouldFee(),
                DisplayFormatters.formatIdrAmount(lender.shouldFee()),
                lender.shouldPenInterest(),
                DisplayFormatters.formatIdrAmount(lender.shouldPenInterest()),
                lender.shouldInitLateFee(),
                DisplayFormatters.formatIdrAmount(lender.shouldInitLateFee()),
                lender.shouldAdvSettleFee(),
                DisplayFormatters.formatIdrAmount(lender.shouldAdvSettleFee()),
                lender.shouldPenalty(),
                DisplayFormatters.formatIdrAmount(lender.shouldPenalty()),
                lender.reductionAmount(),
                DisplayFormatters.formatIdrAmount(lender.reductionAmount()),
                lender.reductionStampDuty(),
                DisplayFormatters.formatIdrAmount(lender.reductionStampDuty()),
                lender.reductionPrincipal(),
                DisplayFormatters.formatIdrAmount(lender.reductionPrincipal()),
                lender.reductionInterest(),
                DisplayFormatters.formatIdrAmount(lender.reductionInterest()),
                lender.reductionFee1(),
                DisplayFormatters.formatIdrAmount(lender.reductionFee1()),
                lender.reductionFee2(),
                DisplayFormatters.formatIdrAmount(lender.reductionFee2()),
                lender.reductionFee3(),
                DisplayFormatters.formatIdrAmount(lender.reductionFee3()),
                lender.reductionFee1Tax(),
                DisplayFormatters.formatIdrAmount(lender.reductionFee1Tax()),
                lender.reductionFee2Tax(),
                DisplayFormatters.formatIdrAmount(lender.reductionFee2Tax()),
                lender.reductionFee3Tax(),
                DisplayFormatters.formatIdrAmount(lender.reductionFee3Tax()),
                lender.reductionPenInterest(),
                DisplayFormatters.formatIdrAmount(lender.reductionPenInterest()),
                lender.reductionInitLateFee(),
                DisplayFormatters.formatIdrAmount(lender.reductionInitLateFee()),
                lender.couponAmount(),
                DisplayFormatters.formatIdrAmount(lender.couponAmount()),
                lender.partRepayFlag(),
                lender.paidAmount(),
                DisplayFormatters.formatIdrAmount(lender.paidAmount()),
                RepayTrialVaResponse.from(lender.defaultVa()),
                RepayTrialVaResponse.from(lender.spareVa()),
                RepayTrialVaResponse.from(lender.disabledDefaultVa()),
                lender.couponId(),
                lender.couponType(),
                lender.couponName(),
                lender.userValideDisTime(),
                lender.termNo(),
                termDueDateMillis,
                DisplayFormatters.formatJakartaDate(termDueDateMillis),
                lender.termInfo() == null
                        ? List.of()
                        : lender.termInfo().stream().map(RepayTrialTermResponse::from).toList()
        );
    }

    private static Long toMillis(Instant instant) {
        return instant == null ? null : instant.toEpochMilli();
    }

    private static BigDecimal sum(BigDecimal left, BigDecimal right) {
        BigDecimal a = left == null ? BigDecimal.ZERO : left;
        BigDecimal b = right == null ? BigDecimal.ZERO : right;
        return a.add(b);
    }
}
