package com.pk.app.repay.dto.response;

import com.pk.core.display.DisplayFormatters;
import com.pk.core.repay.LenderRepayTrialTerm;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public record RepayTrialTermResponse(
        String billNo,
        String loanApplyNo,
        int termNo,
        String termNoDisplay,
        String advSetteFlag,
        BigDecimal schdAmount,
        String schdAmountDisplay,
        BigDecimal schdStampDuty,
        String schdStampDutyDisplay,
        BigDecimal schdPrincipal,
        String schdPrincipalDisplay,
        BigDecimal schdInterest,
        String schdInterestDisplay,
        BigDecimal schdAllFee,
        String schdAllFeeDisplay,
        BigDecimal schdAllTaxFee,
        String schdAllTaxFeeDisplay,
        BigDecimal schdFee1,
        String schdFee1Display,
        BigDecimal schdFee2,
        String schdFee2Display,
        BigDecimal schdFee3,
        String schdFee3Display,
        BigDecimal schdFee1Tax,
        String schdFee1TaxDisplay,
        BigDecimal schdFee2Tax,
        String schdFee2TaxDisplay,
        BigDecimal schdFee3Tax,
        String schdFee3TaxDisplay,
        BigDecimal prePenInterest,
        String prePenInterestDisplay,
        BigDecimal penInterest,
        String penInterestDisplay,
        BigDecimal initLateFee,
        String initLateFeeDisplay,
        Long dueDate,
        String dueDateDisplay,
        Integer overdueDays,
        Long graceDate,
        String graceDateDisplay,
        String termStatus,
        Long daysOfDueDate,
        BigDecimal shouldAmount,
        String shouldAmountDisplay,
        BigDecimal shouldStampDuty,
        String shouldStampDutyDisplay,
        BigDecimal shouldPrincipal,
        String shouldPrincipalDisplay,
        BigDecimal shouldInterest,
        String shouldInterestDisplay,
        BigDecimal shouldFee1,
        String shouldFee1Display,
        BigDecimal shouldFee2,
        String shouldFee2Display,
        BigDecimal shouldFee3,
        String shouldFee3Display,
        BigDecimal shouldFee1Tax,
        String shouldFee1TaxDisplay,
        BigDecimal shouldFee2Tax,
        String shouldFee2TaxDisplay,
        BigDecimal shouldFee3Tax,
        String shouldFee3TaxDisplay,
        BigDecimal shouldPenInterest,
        String shouldPenInterestDisplay,
        BigDecimal shouldInitLateFee,
        String shouldInitLateFeeDisplay,
        String partRepayFlag,
        BigDecimal paidAmount,
        String paidAmountDisplay,
        BigDecimal couponDiscount,
        String couponDiscountDisplay,
        BigDecimal reductionAmount,
        String reductionAmountDisplay,
        List<RepayTrialDiscountInfoResponse> discountInfos
) {
    public static RepayTrialTermResponse from(LenderRepayTrialTerm term) {
        Long dueDateMillis = toMillis(term.dueDate());
        Long graceDateMillis = toMillis(term.graceDate());
        return new RepayTrialTermResponse(
                term.billNo(),
                term.loanApplyNo(),
                term.termNo(),
                DisplayFormatters.formatTermNo(term.termNo()),
                term.advSetteFlag(),
                term.schdAmount(),
                DisplayFormatters.formatIdrAmount(term.schdAmount()),
                term.schdStampDuty(),
                DisplayFormatters.formatIdrAmount(term.schdStampDuty()),
                term.schdPrincipal(),
                DisplayFormatters.formatIdrAmount(term.schdPrincipal()),
                term.schdInterest(),
                DisplayFormatters.formatIdrAmount(term.schdInterest()),
                term.schdAllFee(),
                DisplayFormatters.formatIdrAmount(term.schdAllFee()),
                term.schdAllTaxFee(),
                DisplayFormatters.formatIdrAmount(term.schdAllTaxFee()),
                term.schdFee1(),
                DisplayFormatters.formatIdrAmount(term.schdFee1()),
                term.schdFee2(),
                DisplayFormatters.formatIdrAmount(term.schdFee2()),
                term.schdFee3(),
                DisplayFormatters.formatIdrAmount(term.schdFee3()),
                term.schdFee1Tax(),
                DisplayFormatters.formatIdrAmount(term.schdFee1Tax()),
                term.schdFee2Tax(),
                DisplayFormatters.formatIdrAmount(term.schdFee2Tax()),
                term.schdFee3Tax(),
                DisplayFormatters.formatIdrAmount(term.schdFee3Tax()),
                term.prePenInterest(),
                DisplayFormatters.formatIdrAmount(term.prePenInterest()),
                term.penInterest(),
                DisplayFormatters.formatIdrAmount(term.penInterest()),
                term.initLateFee(),
                DisplayFormatters.formatIdrAmount(term.initLateFee()),
                dueDateMillis,
                DisplayFormatters.formatJakartaDate(dueDateMillis),
                term.overdueDays(),
                graceDateMillis,
                DisplayFormatters.formatJakartaDate(graceDateMillis),
                term.termStatus(),
                term.daysOfDueDate(),
                term.shouldAmount(),
                DisplayFormatters.formatIdrAmount(term.shouldAmount()),
                term.shouldStampDuty(),
                DisplayFormatters.formatIdrAmount(term.shouldStampDuty()),
                term.shouldPrincipal(),
                DisplayFormatters.formatIdrAmount(term.shouldPrincipal()),
                term.shouldInterest(),
                DisplayFormatters.formatIdrAmount(term.shouldInterest()),
                term.shouldFee1(),
                DisplayFormatters.formatIdrAmount(term.shouldFee1()),
                term.shouldFee2(),
                DisplayFormatters.formatIdrAmount(term.shouldFee2()),
                term.shouldFee3(),
                DisplayFormatters.formatIdrAmount(term.shouldFee3()),
                term.shouldFee1Tax(),
                DisplayFormatters.formatIdrAmount(term.shouldFee1Tax()),
                term.shouldFee2Tax(),
                DisplayFormatters.formatIdrAmount(term.shouldFee2Tax()),
                term.shouldFee3Tax(),
                DisplayFormatters.formatIdrAmount(term.shouldFee3Tax()),
                term.shouldPenInterest(),
                DisplayFormatters.formatIdrAmount(term.shouldPenInterest()),
                term.shouldInitLateFee(),
                DisplayFormatters.formatIdrAmount(term.shouldInitLateFee()),
                term.partRepayFlag(),
                term.paidAmount(),
                DisplayFormatters.formatIdrAmount(term.paidAmount()),
                term.couponDiscount(),
                DisplayFormatters.formatIdrAmount(term.couponDiscount()),
                term.reductionAmount(),
                DisplayFormatters.formatIdrAmount(term.reductionAmount()),
                term.discountInfos() == null
                        ? List.of()
                        : term.discountInfos().stream().map(RepayTrialDiscountInfoResponse::from).toList()
        );
    }

    private static Long toMillis(Instant instant) {
        return instant == null ? null : instant.toEpochMilli();
    }
}
